"""Core domain models for the Terminal Ledger App.

繁中：定義純資料結構，不耦合任何 UI / Android / Web API，方便跨平台重用。
English: Defines pure data structures without UI/Android/Web dependencies for cross-platform reuse.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from decimal import Decimal


@dataclass
class Transaction:
    """單筆交易資料 / Single transaction record.

    繁中：
    - id: 交易唯一識別碼（由 service 產生）。
    - amount: 金額，正數代表收入、負數代表支出。
    - category: 分類（依規格需為 ASCII）。
    - note: 備註（可選）。
    - occurred_at: 交易發生時間（用來判定月份歸屬）。
    - created_at: 建立紀錄時間。
    - deleted: 軟刪除旗標（保留歷史、避免硬刪）。

    English:
    - id: Unique transaction identifier generated by the service.
    - amount: Positive for income, negative for expense.
    - category: Category name (ASCII-only by spec).
    - note: Optional free-text note.
    - occurred_at: Business event time used for month grouping.
    - created_at: Record creation timestamp.
    - deleted: Soft-delete flag (history retained).
    """

    id: int
    amount: Decimal
    category: str
    note: str | None
    occurred_at: datetime
    created_at: datetime
    deleted: bool = False


@dataclass
class MonthlyStats:
    """月份統計結果 / Monthly aggregate result.

    繁中：income（>0）、expense（<0）、net（income + expense）。
    English: income (>0), expense (<0), and net (income + expense).
    """

    income: Decimal
    expense: Decimal
    net: Decimal
